WF trigger on multiple ways

diff --git a/.github/workflows/simple.yaml b/.github/workflows/simple.yaml
--- a/.github/workflows/simple.yaml
+++ b/.github/workflows/simple.yaml
@@ -1,20 +1,20 @@
-name: Building first workfloe blocks
+# name: Building first workfloe blocks
 
-on: push
+# on: push
 
-jobs:
-    job1:
-        runs-on: ubuntu-latest
-        steps:
-            - name: step1
-              run: echo "Run step1!"
+# jobs:
+#     job1:
+#         runs-on: ubuntu-latest
+#         steps:
+#             - name: step1
+#               run: echo "Run step1!"
 
-    job2:
-        runs-on: ubuntu-latest
-        steps:
-            - name: failed step
-              run: |
-                echo "I failed"
-                exit 1              # terminate process execution
-            - name: failed
-              run: echo "Goodbye"
+#     job2:
+#         runs-on: ubuntu-latest
+#         steps:
+#             - name: failed step
+#               run: |
+#                 echo "I failed"
+#                 exit 1              # terminate process execution
+#             - name: failed
+#               run: echo "Goodbye"
